### ISSUE TITLE
Favoriting Weapons & Clicking them from the Combat Style prompts all notes

### ISSUE THREAD

**Issue by pvt900** [DigitalPagan/Mythras-Roll20-Sheet#68]
As title mentions, When favoriting a weapon on the updated sheet and clicking the weapon on the Combat Style Roll Card in Chat it appends all character notes to the "notes" section of the sheet.

**Comment by pvt900** [comment]
![image](https://github.com/DigitalPagan/Mythras-Roll20-Sheet/assets/53491379/e7d9c77b-9af8-4047-8944-ed3151281a3f)

**Comment by pvt900** [comment]
![image](https://github.com/DigitalPagan/Mythras-Roll20-Sheet/assets/53491379/6350900d-20b1-4391-9c79-d74cd2d2cf27)


It appears the notes sections at the bottom get appended and even if they're removed they still appear when clicked.

**Comment by DigitalPagan** [comment]
Thanks for sharing.  I did some initial investigation and think I understand the problem as a Roll20 bug with the way to treats names in repeating fields.  I tried some ideas in testing and seemed to find a fix for close combat weapons but the ranged weapons are being weirdly unresponsive to the same fix.

This will likely need to be fixed in v3.1 as it will probably require some renaming of variables but I'll try asking Roll20 support and see if they have a better idea to address this issue.

Thanks,

**Comment by DigitalPagan** [comment]
Got reports this is still happening.  I have plans to try and switch to custom rolls (https://wiki.roll20.net/Custom_Roll_Parsing) which I am hoping will fix some of these issues because it will completely alter the way data is feed into the roll templates, potentially bypassing these bugs.

**Comment by DigitalPagan** [comment]
Fixed in v3.4
